version = 1
SPDX-PackageName = "FOSS Public Alert Server"
SPDX-PackageSupplier = "Nucleus <nucleus-ffm@posteo.de>, Volker Krause <vkrause@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/webapps/foss-public-warn-server"

[[annotations]]
path = ["foss_public_alert_server/alertHandler/data/EMMA_ID/**.geojson", "foss_public_alert_server/alertHandler/data/NUTS3/**.geojson", "foss_public_alert_server/alertHandler/data/FIPS/**.geojson", "foss_public_alert_server/alertHandler/data/WARNCELLID/5**.geojson"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Meteoalarm / EUMETNET"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "foss_public_alert_server/alertHandler/data/WARNCELLID/2**.geojson"
precedence = "aggregate"
SPDX-FileCopyrightText = "Source: Deutscher Wetterdienst"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["foss_public_alert_server/alertHandler/data/SAME/**.geojson", "foss_public_alert_server/alertHandler/data/UGC/**.geojson"]
precedence = "aggregate"
SPDX-FileCopyrightText = "National Weather Service (NWS)"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["foss_public_alert_server/alertHandler/data/Taiwan_Geocode_103/**.geojson", "foss_public_alert_server/alertHandler/data/Taiwan_Geocode_106/**.geojson", "foss_public_alert_server/alertHandler/data/Taiwan_Geocode_107/**.geojson", "foss_public_alert_server/alertHandler/data/Taiwan_Geocode_112/**.geojson", "foss_public_alert_server/alertHandler/data/Taiwan_Geocode_113/**.geojson"]
precedence = "aggregate"
SPDX-FileCopyrightText = "National Science and Technology Center for Disaster Reduction (NCDR)"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "foss_public_alert_server/alertHandler/data/AMOC-AreaCode/**.geojson"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright Commonwealth of Australia 2025, Bureau of Meteorology (ABN 92 637 533 532)"
SPDX-License-Identifier = "LicenseRef-BoM"

[[annotations]]
path = "foss_public_alert_server/alertHandler/data/ISO3166-2/**.geojson"
precedence = "aggregate"
SPDX-FileCopyrightText = "OpenStreetMap"
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = "foss_public_alert_server/alertHandler/data/CPEAS Geographic Code/**.geojson"
precedence = "aggregate"
SPDX-FileCopyrightText = "GaryBikini (https://github.com/GaryBikini/ChinaAdminDivisonSHP)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "foss_public_alert_server/alertHandler/data/LGD District Code/**.geojson"
precedence = "aggregate"
SPDX-FileCopyrightText = "Ministry of Panchayati Raj/Government of India"
SPDX-License-Identifier = "LicenseRef-MPR"

[[annotations]]
path = ["foss_public_alert_server/manage.py", "foss_public_alert_server/alertHandler/migrations/**.py", "foss_public_alert_server/subscriptionHandler/migrations/**.py", "foss_public_alert_server/sourceFeedHandler/migrations/**.py", "foss_public_alert_server/configuration/migrations/**.py", "foss_public_alert_server/alertTester/migrations/**.py"]
precedence = "aggregate"
SPDX-FileCopyrightText = "auto-generated by Django"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["foss_public_alert_server/aggregated_feeds.json", "foss_public_alert_server/sourceFeedHandler/custom_feeds.json", "foss_public_alert_server/sourceFeedHandler/dead_feeds.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "FOSS Public Alert Server"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["foss_public_alert_server/sourceFeedHandler/static/css/**", "foss_public_alert_server/sourceFeedHandler/static/js/**", "foss_public_alert_server/sourceFeedHandler/templates/**", "foss_public_alert_server/sourceFeedHandler/fixtures/**", "foss_public_alert_server/configuration/fixtures/**", "foss_public_alert_server/configuration/templates/**", "foss_public_alert_server/configuration/static/**", "foss_public_alert_server/alertTester/templates/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "FOSS Public Alert Server"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["foss_public_alert_server/alertHandler/data/broken-chains.pem", "foss_public_alert_server/lib/testdata/**.xml", "foss_public_alert_server/lib/testdata/**.json", "foss_public_alert_server/lib/testdata/**.geojson", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["logo.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "FOSS Public Alert Server"
SPDX-License-Identifier = "AGPL-3.0-or-later"
