# Generated by Django 5.2.14 on 2026-07-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptionHandler", "0010_connectionflag_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="vapid_public_key",
            field=models.CharField(max_length=96, null=True),
        ),
    ]
