# SPDX-FileCopyrightText: Nucleus <nucleus-ffm@posteo.de>
# SPDX-FileCopyrightText: Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Django settings for foss_public_alert_server project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import logging.config
from pathlib import Path
from django.utils.log import DEFAULT_LOGGING

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANOG_SECRET_KEY', 'django-insecure-)auz7%gl8fg)i-w!e5srhx2&na7rd(e^nok!&i)qsv1a5olz&k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if os.getenv('DJANGO_DEBUG', '') == 'True':
    DEBUG = True

ALLOWED_HOSTS = os.getenv('DJANOG_ALLOWED_HOSTS', 'localhost;127.0.0.1;10.0.2.2;aggregator').split(';')

# Allow to set CSRF_TRUSTED_ORIGINS as an environment variable but default to an empty list
CSRF_TRUSTED_ORIGINS = os.getenv('DJANOG_CSRF_TRUSTED_ORIGINS').split(';') if os.getenv('DJANOG_CSRF_TRUSTED_ORIGINS') else []

# Application definition

INSTALLED_APPS = [
    'subscriptionHandler.apps.SubscriptionHandlerConfig',
    'alertHandler.apps.AlertHandlerConfig',
    'sourceFeedHandler.apps.SourcefeedhandlerConfig',
    'alertTester.apps.AlertTesterConfig',
    'configuration.apps.ConfigurationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_celery_beat',
    'django_prometheus',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'foss_public_alert_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'foss_public_alert_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DATABASE', 'foss-public-alert-server'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'POST': os.environ.get('POSTGRES_PORT', '5432'),
    },

    'default_alt': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_X_FORWARDED_HOST = os.getenv('DJANGO_USE_X_FORWARDED', False)
USE_X_FORWARDED_PORT = os.getenv('DJANGO_USE_X_FORWARDED', False)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', BASE_DIR.joinpath('static'))

MEDIA_URL = 'cap/'
MEDIA_ROOT = os.getenv('DJANGO_MEDIA_ROOT', BASE_DIR.joinpath('cap'))

USER_AGENT = "FOSS Public Alert Server"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# timeperiod in seconds for feed updates used by the celery task scheduler
DEFAULT_UPDATE_PERIOD_FOR_CAP_FEEDS = 60

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery config
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# for Celery metrics exporter
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# RabitMQ server URL for Celery
AMQP_URL = os.getenv('AMQP_URL', 'amqp://localhost')

# Default settings for the server. The values can be changed at runtime in the admin interface
DEFAULT_SETTINGS = [
    # name, datatype, default value
    # timeperiod after which an inactive subscription without heartbeats will be deleted from the database
    ["DAYS_INACTIVE_TIMEOUT", "int", 365],

    # for every failed push notification for a subscription, we increase a counter.
    # If the counter reaches the limit, the subscription is deleted
    ["NUMBER_OF_PUSH_ERRORS_BEFORE_DELETING", "int", 10],

    # server config for clients
    ["OPERATOR", "char", "Example"],
    ["PRIVACY_NOTICE", "char", "https://example.com"],
    ["TERMS_OF_SERVICE", "char", "https://example.com"],

    # defines which push services the server is capable of
    ["SUPPORT_UNIFIED_PUSH", "bool", True],
    ["SUPPORT_UNIFIED_PUSH_ENCRYPTED", "bool", True],
    ["SUPPORT_APN", "bool", False],
    ["SUPPORT_FIREBASE", "bool", False],

    # is a metric for clients to see if this client is near its capacity limit
    # in the future this value will be automatically calculated.
    ["CONGESTION_STATE", "int",  1],
    ["VERSION", "char", "0.1.0"]
]

# webpush config
# SECURITY WARNING: keep the private key used in production secret!
WEB_PUSH_CONFIG_PRIVATE_KEY = os.environ.get('WEB_PUSH_CONFIG_PRIVATE_KEY', 'tiQpqhJBxAAEwxbDQ2OYiQoJ1j18NLEn-Qm09oxte0Q')
WEB_PUSH_CONFIG_PUBLIC_KEY = os.environ.get('WEB_PUSH_CONFIG_PUBLIC_KEY', 'BHJnBOSvBJ9Vl0fF44dUFxmr3l-mNSjuAGvIsFKBSWUsBu2-v2dov1UcGgE2Ry_yjJsz38F3a0A-QrAjCr3OCA4')

WEB_PUSH_CONTACT =  os.environ.get("WEB_PUSH_CONTACT", "mailto:todo@example.com")

# Logging config

# Disable Django's logging setup
LOGGING_CONFIG = None

LOGLEVEL = os.environ.get('LOGLEVEL', 'info').upper()

logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            # exact format is not important, this is the minimum information
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
        'django.server': DEFAULT_LOGGING['formatters']['django.server'],
    },
    'handlers': {
        # console logs to stderr
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
        'django.server': DEFAULT_LOGGING['handlers']['django.server'],
    },
    'loggers': {
        # default for all undefined Python modules
        '': {
            'level': 'WARNING',
            'handlers': ['console'],
        },
        # Our application code
        'app': {
            'level': LOGLEVEL,
            'handlers': ['console'],
            # Avoid double logging because of root logger
            'propagate': False,
        },
        # Default runserver request logging
        'django.server': DEFAULT_LOGGING['loggers']['django.server'],
    },
})
